- name: Nvidia
  become: true
  pacman:
    name:
      - linux-headers 
      - nvidia-dkms 
      - nvidia-settings 
      - libva 
      - libva-nvidia-driver-git
  tags: 
    - preinstall
    - desktop
