---

- name: Test
  ansible.builtin.set_fact:
    test_dist: "{{ ansible_facts['distribution'] }}"

- name: Debug
  debug:
    msg: "{{ ansible_facts['test_dist'] }}"

- name: "{{ role_name }} | Checking for Distribution config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts[distribution] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts[distribution] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts[distribution] }}.yml"
  when: distribution_config.stat.exists
